#ifndef OPENVPN_LEGAL_COPYRIGHT_H
#define OPENVPN_LEGAL_COPYRIGHT_H

const char openvpn_copyright[] = // CONST GLOBAL
//  Copyright (c) 2012 OpenVPN Technologies, Inc. All rights reserved.
  "\n"
  "----------------------------\n"
  "\n"
  "This package includes OpenSSL, Copyright (c) 1998-2011 The OpenSSL Project. All rights reserved.\n"
  "\n"
  "OpenSSL License:\n"
  "Redistribution and use in source and binary forms, with or without\n"
  "modification, are permitted provided that the following conditions\n"
  "are met:\n"
  "1. Redistributions of source code must retain the above copyright\n"
  "   notice, this list of conditions and the following disclaimer.\n"
  "2. Redistributions in binary form must reproduce the above copyright\n"
  "   notice, this list of conditions and the following disclaimer in\n"
  "   the documentation and/or other materials provided with the\n"
  "   distribution.\n"
  "3. All advertising materials mentioning features or use of this\n"
  "   software must display the following acknowledgment:\n"
  "   \"This product includes software developed by the OpenSSL Project\n"
  "   for use in the OpenSSL Toolkit. (http://www.openssl.org/)\"\n"
  "4. The names \"OpenSSL Toolkit\" and \"OpenSSL Project\" must not be used to\n"
  "   endorse or promote products derived from this software without\n"
  "   prior written permission. For written permission, please contact\n"
  "   openssl-core@openssl.org.\n"
  "5. Products derived from this software may not be called \"OpenSSL\"\n"
  "   nor may \"OpenSSL\" appear in their names without prior written\n"
  "   permission of the OpenSSL Project.\n"
  "6. Redistributions of any form whatsoever must retain the following\n"
  "   acknowledgment:\n"
  "   \"This product includes software developed by the OpenSSL Project\n"
  "   for use in the OpenSSL Toolkit (http://www.openssl.org/)\"\n"
  "THIS SOFTWARE IS PROVIDED BY THE OpenSSL PROJECT ``AS IS'' AND ANY\n"
  "EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE\n"
  "IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR\n"
  "PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE OpenSSL PROJECT OR\n"
  "ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\n"
  "SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT\n"
  "NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\n"
  "LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)\n"
  "HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,\n"
  "STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)\n"
  "ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED\n"
  "OF THE POSSIBILITY OF SUCH DAMAGE.\n";

#endif
