#!/usr/bin/env bash
set -e
if [ -z "$O3" ]; then
    echo O3 var must point to ovpn3 tree
    exit 1
fi
cd ~/linux
$O3/scripts/linux/build-boost
$O3/scripts/linux/build-openssl x64
$O3/scripts/linux/build-polarssl
$O3/scripts/linux/build-snappy
$O3/scripts/linux/build-lz4
$O3/scripts/linux/build-lzo
$O3/scripts/linux/consolidate-so
