#!/usr/bin/env bash
set -e
export OPENSSL=openssl-1.0.1c
export DIST=$(pwd)/openssl-dist
rm -rf $OPENSSL $DIST
tar xfz $DL/$OPENSSL.tar.gz
cd $OPENSSL
./Configure linux-x86_64 no-shared threads no-idea no-mdc2 no-rc5 --prefix=$DIST
#sed -i -e 's|-O3|-O3 -fPIC|' Makefile
make -j 4 build_libs
touch apps/openssl
touch openssl.pc
touch libcrypto.pc
touch libssl.pc
make install_sw
