#!/usr/bin/env bash
set -e
. $O3/lib-versions
export DIST=$(pwd)/lzo/lzo-linux
rm -rf $LZO_VERSION $DIST
mkdir -p $DIST
tar xfz $DL/$LZO_VERSION.tar.gz
cd $LZO_VERSION
CFLAGS="" ./configure --prefix=$DIST --enable-shared --disable-static
make
make install
