#!/usr/bin/env bash
set -e
. $O3/lib-versions
export DIST=$(pwd)/lzo
rm -rf $LZO_VERSION $DIST
tar xfz $DL/$LZO_VERSION.tar.gz
cd $LZO_VERSION
CFLAGS="-g" ./configure --prefix=$DIST --enable-shared --disable-static
make
make install
