#!/usr/bin/env bash
set -e
. $O3/lib-versions
export DIST=$(pwd)/snappy/snappy-linux
rm -rf $SNAPPY_VERSION $DIST
mkdir -p $DIST
tar xfz $DL/$SNAPPY_VERSION.tar.gz
cd $SNAPPY_VERSION
CFLAGS="" ./configure --prefix=$DIST
make
make install
