#!/usr/bin/env bash
set -e
if [ -z "$O3" ]; then
    export O3="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../.." && pwd )"
fi
export DEP_DIR=${DEP_DIR:-$HOME/linux}
cd $DEP_DIR
$O3/scripts/linux/build-boost
#$O3/scripts/linux/build-openssl x64
$O3/scripts/linux/build-polarssl
$O3/scripts/linux/build-snappy
$O3/scripts/linux/build-lz4
$O3/scripts/linux/build-lzo
#$O3/scripts/linux/consolidate-so
