#!/usr/bin/env bash
rm -rf so
mkdir so
OPT=-d
cp $OPT boost/stage-linux/lib/lib* so/
cp $OPT lzo/lzo-linux/lib/lib* so/
cp $OPT openssl/openssl-linux/lib/lib* so/
cp $OPT snappy/snappy-linux/lib/lib* so/
cp $OPT polarssl/polarssl-linux/library/lib* so/
