#!/bin/bash
GCC_EXTRA="$GCC_EXTRA -DOPENVPN_SHOW_SESSION_TOKEN"
[ "$EER" = "1" ] && GCC_EXTRA="$GCC_EXTRA -DTEST_EER"
[ "$NULL" = "1" ] && GCC_EXTRA="$GCC_EXTRA -DOPENVPN_FORCE_TUN_NULL"
[ "$EXIT" = "1" ] && GCC_EXTRA="$GCC_EXTRA -DTUN_NULL_EXIT"
export GCC_EXTRA
if [ "$(uname)" == "Darwin" ]; then
    cd $O3/core
    . vars/vars-osx64
    . vars/setpath
    cd test/ovpncli
    PSSL=1 LZ4=1 PTPROXY=1 build cli 2>&1
else
    cd $O3/core
    . vars/vars-linux
    . vars/setpath
    cd test/ovpncli
    PSSL=1 LZ4=1 NOSSL=1 PTPROXY=1 build cli 2>&1
fi
