#!/usr/bin/env bash
set -e
. $O3/lib-versions
. $O3/scripts/android/vars
rm -rf openssl
mkdir openssl
for TARGET in android ; do
    . $O3/vars-$TARGET
    export OPENSSL=$OPENSSL_VERSION
    export TPRE=arm-linux-androideabi
    export DIST=$(pwd)/openssl-$PLATFORM
    export BIN=$TC/bin
    rm -rf $DIST
    rm -rf $OPENSSL
    tar xfz ~/Downloads/$OPENSSL.tar.gz
    pushd $OPENSSL
    OSSL_FLAGS="no-shared threads no-idea no-mdc2 no-rc5 no-engine no-comp no-hw no-ssl2 no-ssl3 no-zlib no-rc2 no-cast no-md2 no-ripemd no-camellia no-seed no-krb5 no-socks no-ecdsa no-ec no-ecdh no-md2 no-whirlpool no-dsa no-cms no-jpake no-gost"
    #OSSL_FLAGS="no-shared threads no-comp no-zlib"
    CC="$BIN/$TPRE-gcc" AR="$BIN/$TPRE-ar" RANLIB="$BIN/$TPRE-ranlib" ./Configure linux-armv4 $OSSL_FLAGS --prefix=$DIST
    sed -i "" -e "s|-O3|$LIB_OPT_LEVEL $LIB_FPIC $PLATFORM_FLAGS $OTHER_COMPILER_FLAGS|" Makefile
    sed -i "" -e "s|ERR_load_COMP_strings()|//ERR_load_COMP_strings()|" crypto/err/err_all.c
    make -j 4 build_libs
    touch apps/openssl
    touch openssl.pc
    touch libcrypto.pc
    touch libssl.pc
    make install_sw
    popd
    mv $DIST openssl
done

