#!/usr/bin/env bash
# Build the Android toolchain (run first)
set -e
if [ -z "$O3" ]; then
    export O3="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../.." && pwd )"
fi
export DEP_DIR=${DEP_DIR:-$HOME/src/android}
cd $DEP_DIR
export NO_MOD_PATH=1
. $O3/android-sdk-path
DEST=$(pwd)/tc
rm -rf $DEST
$NDK/build/tools/make-standalone-toolchain.sh \
    --verbose \
    --ndk-dir=$NDK \
    --toolchain=arm-linux-androideabi-4.8 \
    --stl=gnustl \
    --arch=arm \
    --platform=android-14 \
    --install-dir=$DEST
cd $DEST/arm-linux-androideabi/bin
ln -s ../../bin/arm-linux-androideabi-gcc cc
exit 0
