#!/usr/bin/env bash
# Build Android dependencies (run after build-toolchain)
set -e
if [ -z "$O3" ]; then
    export O3="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../.." && pwd )"
fi
export DEP_DIR=${DEP_DIR:-$HOME/src/android}
cd $DEP_DIR
rm -rf boost* lz4* lzo* minicrypto openssl* polarssl* snappy*
echo "******* BOOST"
$O3/scripts/android/build-boost
echo "******* MINICRYPTO"
$O3/scripts/android/build-minicrypto
echo "******* POLARSSL"
$O3/scripts/android/build-polarssl
#echo "******* OpenSSL"
#$O3/scripts/android/build-openssl-small
#echo "******* LZO"
#$O3/scripts/android/build-lzo
echo "******* SNAPPY"
$O3/scripts/android/build-snappy
echo "******* LZ4"
$O3/scripts/android/build-lz4
