#!/usr/bin/env bash

set -e
if [ -z "$O3" ]; then
    echo O3 var must point to ovpn3 tree
    exit 1
fi
if [ -z "$DEP_DIR" ]; then
    echo DEP_DIR var must point to ovpn3 dependency tree
    exit 1
fi
cd $DEP_DIR

. $O3/android-sdk-path

rm -rf lzo
mkdir lzo

for target in android android-dbg android-a7a android-a7a-dbg ; do
    echo '***************' TARGET $target
    TARGET=$target $O3/lzo/build-lzo
done
exit 0
