#!/usr/bin/env bash

set -e
if [ -z "$O3" ]; then
    echo O3 var must point to ovpn3 tree
    exit 1
fi

. $O3/android-sdk-path

rm -rf lz4
mkdir lz4

for target in android android-dbg android-a7a android-a7a-dbg ; do
    echo '***************' TARGET $target
    TARGET=$target $O3/lz4/build-lz4
done
exit 0
