#!/usr/bin/env bash

set -e
if [ -z "$O3" ]; then
    echo O3 var must point to ovpn3 tree
    exit 1
fi

. $O3/scripts/android/vars

rm -rf lzo
mkdir lzo

for target in android android-dbg ; do
    echo '***************' TARGET $target
    TARGET=$target $O3/lzo/build-lzo
done
