#!/usr/bin/env bash
# Note: thread library may fail with PAGE_SIZE undefined.
# The pthread.h header makes reference to the PAGE_SIZE define however
# this only gets defined in <asm/page.h> which is not pulled in by any
# of the pthread.h includes.  A google-suggested fix was to add
# #include <sys/mman.h>, which does indeed work, but may not be the
# correct solution for all cases.
set -e

# Download Boost
. $O3/lib-versions
[ -z "$DL" ] && DL=~/Downloads
rm -rf boost $BOOST_VERSION
mkdir boost
if [ "$SRCDIR" ]; then
    cp -a "$SRCDIR" $BOOST_VERSION
else
    tar xfz $DL/$BOOST_VERSION.tar.gz
fi
cd $BOOST_VERSION

# Patch it
#patch -p1 <$DL/asio-engine.patch
#patch -p2 <$DL/changeset_75599.diff
#patch -p2 <$DL/changeset_75813.diff || true

# Build builder
./bootstrap.sh

# Put Android NDK cross compiler in PATH
. $O3/android-sdk-path

# Loop over build variants
for TARGET in android android-dbg android-a7a android-a7a-dbg ; do

echo "************************ $TARGET"

. $O3/vars-${TARGET}
btarg="${TARGET//-/}"

cat >>tools/build/v2/user-config.jam <<EOF
using gcc : $btarg : g++
            :
	        <compileflags>"$PLATFORM_FLAGS"
                <compileflags>"$LIB_OPT_LEVEL"
                <compileflags>"$OTHER_COMPILER_FLAGS"
            ; 
EOF

stage=stage-$PLATFORM

if [ "$DEBUG_BUILD" = "1" ]; then
	variant=debug
else
	variant=release
fi

./bjam -d2 toolset=gcc-$btarg --stagedir=$stage --with-system --with-thread variant=$variant link=static threading=multi runtime-link=static

done
mv stage-* ../boost/
cp -a boost ../boost/
exit 0
