#!/usr/bin/env bash

set -e
if [ -z "$O3" ]; then
    echo O3 var must point to ovpn3 tree
    exit 1
fi

rm -rf polarssl
mkdir polarssl

for target in android android-dbg ; do
    echo '***************' TARGET $target
    VERBOSE=1 TARGET=$target CMAKE_TARGET=android USE_MINICRYPTO=1 MINICRYPTO_DIR=$(pwd)/minicrypto/minicrypto-$target $O3/polarssl/build-polarssl
    mv polarssl-$target polarssl/
done
