#!/usr/bin/env bash
top=$(pwd)

# openvpn core
find openvpn | grep -E '\.(cpp|hpp|c|h)$'

# core API
echo client/ovpncli.hpp
echo client/ovpncli.cpp

# Java API
echo javacli/OpenVPNClientThread.java

# Android client
android=android/OpenVPN/src/net/openvpn/openvpn
cd $android
for f in $(git ls-files | grep '\.java$') ; do
    echo $android/$f
done
cd $top

# iOS client
echo ios/OpenVPN/OpenVPNPlugin/OpenVPNPlugin.h
echo ios/OpenVPN/OpenVPNPlugin/OpenVPNPlugin.cpp
ls ios/OpenVPN/OpenVPNPlugin/pluginutil.*
iosapp=ios/OpenVPN/OpenVPNApp-iOS
cd $iosapp
for f in *.h *.m *.mm *.hpp *.cpp ; do
    echo $iosapp/$f
done
cd $top
