#!/bin/bash
if [ "$(uname)" == "Darwin" ]; then
    cd $O3/core
    . vars/vars-osx64
    . vars/setpath
    cd test/ssl
    # GCC_EXTRA="-DENABLE_PRNG" HYBRID=1
    PSSL=1 build proto 2>&1
else
    cd $O3/core
    . vars/vars-linux
    . vars/setpath
    cd test/ssl
    #GCC_EXTRA="-DENABLE_PRNG"
    PSSL=1 NOSSL=1 build proto 2>&1
fi
