#!/bin/bash
if [ "$(uname)" == "Darwin" ]; then
    cd $O3/core
    . vars/vars-osx64
    . vars/setpath
    cd test/ssl
    # GCC_EXTRA="-DENABLE_PRNG" HYBRID=1
    PSSL=1 build proto
else
    cd $O3/core
    . vars/vars-linux
    . vars/setpath
    cd test/ssl
    #GCC_EXTRA="-DENABLE_PRNG"
    if [ "$OSSL" = "1" ]; then
	OSSL=1 build proto
    else
	PSSL=1 NOSSL=1 build proto
    fi
fi
