#!/usr/bin/env bash

# flags
#export GCC_EXTRA="-DITER=10001 -DSITER=100" 

echo "*** Apple SSL client -> Apple default OpenSSL server (0.9.8)"
OPENSSL_DIR="" SSL_BOTH=1 build proto && time ./proto

echo "*** Apple SSL client -> Apple OpenSSL 1.x server"
SSL_BOTH=1 build proto && time ./proto

echo "*** OpenSSL client -> OpenSSL server"
OSSL=1 build proto && time ./proto

echo "*** PolarSSL client -> OpenSSL server"
PSSL=1 OSSL=1 build proto && time ./proto
