#!/usr/bin/env bash
#
# Parameters:
#   CMAKE_TARGET -- use $CMAKE_TARGET.cmake as toolchain file
#   AES_NI=1 -- enable AES_NI processor optimization
#   EXTERNAL_RNG=1 -- disable all internal RNG implementations (caller must provide)
#   ENABLE_TESTING=1 -- run PolarSSL test scripts after build
#   ENABLE_SERVER=1  -- enable SSL/TLS server code
#   VERBOSE=1 -- see build commands
#   USE_MINICRYPTO=1 -- use minicrypto library
#   NO_WIPE=1 -- don't wipe source tree and reunzip tarball
#
# Examples:
#   AES_NI=1 $O3/polarssl/build-polarssl
#   AES_NI=1 ENABLE_TESTING=1 VERBOSE=1 $O3/polarssl/build-polarssl

set -e
if [ -z "$O3" ]; then
    echo O3 var must point to ovpn3 tree
    exit 1
fi
if [ -z "$TARGET" ]; then
    echo TARGET var must be defined
    exit 1
fi

# source vars
. $O3/vars-${TARGET}
. $O3/lib-versions

# extract the PolarSSL source
PD=$O3/polarssl
DIST=polarssl-$PLATFORM

rm -rf $DIST
mkdir $DIST

if [ "$NO_WIPE" = "1" ]; then
    echo RETAIN existing source
    cd $POLARSSL_VERSION
else
    echo WIPE and reunzip source
    rm -rf $POLARSSL_VERSION
    [ -z "$DL" ] && DL=~/Downloads
    tar xfz $DL/$POLARSSL_VERSION-gpl.tgz

    cd $POLARSSL_VERSION

    # delete makefiles (apparently not needed)
    rm $(find . -type f | grep Makefile)

    # patch it
    cd library
    echo PATCH trustex.patch
    patch <$PD/trustex.patch
    cd ..
    echo PATCH polarssl-enum.patch
    patch -p1 <$PD/polarssl-enum.patch
    echo PATCH polarssl-const-ciphersuite.patch
    patch -p1 <$PD/polarssl-const-ciphersuite.patch
    echo PATCH polarssl-epki.patch
    patch -p1 <$PD/polarssl-epki.patch
    #echo PATCH polarssl-invalid-mac.patch
    #patch -p1 <$PD/polarssl-invalid-mac.patch 

    # do the big polar-openssl patch
    if [ "$USE_MINICRYPTO" = "1" ]; then
	echo MERGING polar-openssl.patch
	patch -p1 <$PD/polar-openssl.patch
    fi

    # define configs
    cp $PD/config.h include/polarssl/
    cp $PD/CMakeLists.txt .
fi

# set options
OPT=""

# RNG
if [ "$EXTERNAL_RNG" = "1" ]; then
    OPT="$OPT -DEXTERNAL_RNG=1"
fi

# enable testing?
if [ "$ENABLE_TESTING" = "1" ]; then
    OPT="$OPT -DENABLE_TESTING=1"
fi
if [ "$DEBUG_BUILD" = "1" ]; then
    OPT="$OPT -DENABLE_SELF_TEST=1"
fi

# configure target
if [ "$CMAKE_TARGET" ]; then
    OPT="$OPT -DCMAKE_TOOLCHAIN_FILE=$PD/$CMAKE_TARGET.cmake"
elif [ "$APPLE_FAMILY" = "1" ]; then
    OPT="$OPT -DCMAKE_TOOLCHAIN_FILE=$PD/apple.cmake"
fi

# OpenSSL
if [ "$USE_MINICRYPTO" = "1" ]; then
    OPT="$OPT -DMINICRYPTO=1"
    if [ "$MINICRYPTO_DIR" ]; then
	OPT="$OPT -DMINICRYPTO_DIR=$MINICRYPTO_DIR"
    fi
    if [ "$AES_NI" = "1" ]; then
	OPT="$OPT -DOPENSSL_AES_NI=1"
    fi
fi

# Enable SSL/TLS server
if [ "$ENABLE_SERVER" = "1" ]; then
    OPT="$OPT -DENABLE_SERVER=1"
fi

# Build shared library
if [ "$SHARED" = "1" ]; then
    OPT="$OPT -DUSE_SHARED_POLARSSL_LIBRARY=1"
fi

# echo options
echo OPTIONS $OPT

# build it
pwd
cd ../$DIST
cmake $OPT ../$POLARSSL_VERSION
if [ "$VERBOSE" = "1" ]; then
    make VERBOSE=1
else
    make
fi

# test it
if [ "$ENABLE_TESTING" = "1" ]; then
    make test
fi

# copy headers
cp -a ../$POLARSSL_VERSION/include/polarssl include/
