#!/usr/bin/env bash
set -e
POLARSSL_SRC=$HOME/src/mac/polarssl-1.2.7
PD=$O3/polarssl
PB=$(basename $POLARSSL_SRC)

rm -rf polartmp
mkdir polartmp
cd polartmp
cp -a $POLARSSL_SRC polarssl.new

# extract the PolarSSL source
tar xfz $DL/$PB-gpl.tgz

cd $PB
rm $(find . -type f | grep -E 'Makefile|\.orig$|\.rej$')
rm CMakeLists.txt include/polarssl/config.h

cd ../polarssl.new
rm CMakeLists.txt include/polarssl/config.h
cd ..

diff -uNr $PB polarssl.new >$PD/polar-openssl.patch
