#!/usr/bin/env bash
# generate expire time in python: time.mktime((2012, 5, 1, 0, 0, 0, 0, 0, -1))
set -e

rm_generated_files()
{
    svn status --no-ignore | perl -nle 's/\\/\//g; print "rm -rf '\''$1'\''" if /^[\?I]\s+([\S\t\x20]+)/;' | sh
}

rm_generated_files

if [ "$PT" = "1" ]; then
    pkg=net.openvpn.privatetunnel
    rm -rf pt
    mkdir pt
else
    pkg=net.openvpn.openvpn
fi

if [ "$DEBUG_BUILD" = "1" ]; then
    vis1=""
    vis2=""
    opt2="$LIB_OPT_LEVEL"
else
    vis1="-fvisibility=hidden"
    vis2='-DSWIGEXPORT=__attribute__((visibility("default")))'
    opt2="-Os"
fi

echo SWIG
swig -c++ -java -package $pkg -I$O3/client -I$O3 ovpncli.i

echo CORE
$GPP_CMD \
    --sysroot=$NDK/platforms/android-9/arch-arm \
    -DAPP_EXPIRE_TIME=1364796000 \
    $LIB_OPT_LEVEL $LIB_FPIC \
    -Wall -Wno-sign-compare -Wno-unused-parameter \
    $vis1 \
    -DUSE_POLARSSL \
    -DHAVE_SNAPPY \
    -D__GLIBC__ \
    -D_GLIBCXX_HAVE_FENV_H=1 \
    -DBOOST_NO_INTRINSIC_WCHAR_T \
    -I$O3/client \
    -I$O3 \
    -I$DEP_DIR/boost \
    -I$DEP_DIR/polarssl/polarssl-$PLATFORM/include \
    -I$DEP_DIR/lzo/lzo-$PLATFORM/include \
    -I$DEP_DIR/snappy/snappy-$PLATFORM/include \
    -c $O3/client/ovpncli.cpp

echo WRAP
$GPP_CMD \
    --sysroot=$NDK/platforms/android-9/arch-arm \
    $opt2 $LIB_FPIC \
    -fno-strict-aliasing \
    -Wall \
    $vis1 $vis2 \
    -D__GLIBC__ \
    -D_GLIBCXX_HAVE_FENV_H=1 \
    -I$O3/client \
    -I$O3 \
    -L$DEP_DIR/boost/stage-$PLATFORM/lib \
    -L$DEP_DIR/polarssl/polarssl-$PLATFORM/library \
    -L$DEP_DIR/minicrypto/minicrypto-$PLATFORM \
    -L$DEP_DIR/lzo/lzo-$PLATFORM/lib \
    -L$DEP_DIR/snappy/snappy-$PLATFORM/lib \
    ovpncli_wrap.cxx \
    ovpncli.o \
    -o libovpncli.so \
    -shared -Wl,-soname,libovpncli.so \
    -lpolarssl -lminicrypto \
    -lboost_system -lboost_thread \
    -llzo2 -lsnappy

if [ "$DEBUG_BUILD" != "1" ]; then
    echo STRIP
    $STRIP_CMD libovpncli.so
fi

if [ "$PT" = "1" ]; then
    mv SWIGTYPE_p_std__string.java ClientAPI_*.java libovpncli.so pt/
fi
