#!/usr/bin/env bash
set -e

echo SWIG
swig -c++ -java -I$O3/client -I$O3 ovpncli.i

echo JAVA
javac *.java

echo CORE
gcc -O3 -fPIC -pthread \
    -Wall -Wno-sign-compare -Wno-unused-parameter \
    -fvisibility=hidden \
    -DUSE_POLARSSL \
    -I$O3/client \
    -I$O3 \
    -I$BOOST_DIR \
    -I$POLARSSL_DIR/include \
    -c $O3/client/ovpncli.cpp

echo WRAP
gcc -Os -fPIC -pthread \
    -fno-strict-aliasing \
    -Wall \
    -fvisibility=hidden '-DSWIGEXPORT=__attribute__((visibility("default")))' \
    -I$O3/client \
    -I$O3 \
    -I/usr/lib/jvm/java-7-openjdk-amd64/include \
    -L$BOOST_DIR/stage/lib \
    -L$POLARSSL_DIR/library \
    -L$OPENSSL_DIR/lib \
    ovpncli_wrap.cxx \
    ovpncli.o \
    -o libovpncli.so \
    -shared -Wl,-soname,libovpncli.so \
    -lpolarssl -lminicrypto \
    -lboost_system -lboost_thread

echo STRIP
strip libovpncli.so
