#!/usr/bin/env bash
set -e

if [ -z "$O3" ]; then
    echo O3 var must point to ovpn3 tree
    exit 1
fi

rm_generated_files()
{
    svn status --no-ignore | perl -nle 's/\\/\//g; print "rm -rf '\''$1'\''" if /^[\?I]\s+([\S\t\x20]+)/;' | sh
}

rm_generated_files

echo SWIG
swig -c++ -java -I$O3/core/client -I$O3/core ovpncli.i

echo JAVA
javac *.java

echo CORE
gcc -O3 -fPIC -pthread \
    -Wall -Wno-sign-compare -Wno-unused-parameter \
    -fvisibility=hidden \
    -DUSE_OPENSSL \
    -DHAVE_SNAPPY \
    -I$O3/core/client \
    -I$O3/core \
    -I$DEP_DIR/boost \
    -I$DEP_DIR/openssl/openssl-linux/include \
    -I$DEP_DIR/snappy/snappy-linux/include \
    -c $O3/core/client/ovpncli.cpp

echo WRAP
gcc -Os -fPIC -pthread \
    -fno-strict-aliasing \
    -Wall \
    -fvisibility=hidden '-DSWIGEXPORT=__attribute__((visibility("default")))' \
    -I$O3/core/client \
    -I$O3/core \
    -I/usr/lib/jvm/java-7-openjdk-amd64/include \
    -L$DEP_DIR/boost/stage-linux/lib \
    -L$DEP_DIR/openssl/openssl-linux/lib \
    -L$DEP_DIR/snappy/snappy-linux/lib \
    ovpncli_wrap.cxx \
    ovpncli.o \
    -o libovpncli.so \
    -shared -Wl,-soname,libovpncli.so \
    -lcrypto -lssl \
    -lboost_system -lboost_thread \
    -lsnappy

echo STRIP
strip libovpncli.so
