#!/usr/bin/env bash
# generate expire time in python: time.mktime((2012, 5, 1, 0, 0, 0, 0, 0, -1))
set -e

echo SWIG
swig -c++ -java -package net.openvpn.openvpn -I$OVPN3_DIR ovpncli.i

echo CORE
$GPP_CMD \
    --sysroot=$NDK/platforms/android-9/arch-arm \
    -O3 -fPIC \
    -Wall -Wno-sign-compare -Wno-unused-parameter \
    -fvisibility=hidden \
    -DUSE_POLARSSL \
    -D__GLIBC__ \
    -D_GLIBCXX_HAVE_FENV_H=1 \
    -DBOOST_NO_INTRINSIC_WCHAR_T \
    -I$OVPN3_DIR \
    -I$BOOST_DIR \
    -I$POLARSSL_DIR/include \
    -c ovpncli.cpp

echo WRAP
$GPP_CMD \
    --sysroot=$NDK/platforms/android-9/arch-arm \
    -Os -fPIC \
    -fno-strict-aliasing \
    -Wall \
    -fvisibility=hidden '-DSWIGEXPORT=__attribute__((visibility("default")))' \
    -D__GLIBC__ \
    -D_GLIBCXX_HAVE_FENV_H=1 \
    -I$OVPN3_DIR \
    -L$BOOST_DIR/stage/lib \
    -L$POLARSSL_DIR/library \
    -L$OPENSSL_DIR/lib \
    ovpncli_wrap.cxx \
    ovpncli.o \
    -o libovpncli.so \
    -shared -Wl,-soname,libovpncli.so \
    -lpolarssl -lminicrypto \
    -lboost_system -lboost_thread

echo STRIP
$STRIP_CMD libovpncli.so
