#!/usr/bin/env bash
# generate expire time in python: time.mktime((2012, 5, 1, 0, 0, 0, 0, 0, -1))
set -e

rm -rf pt
mkdir pt

echo SWIG
swig -c++ -java -package net.openvpn.privatetunnel -I$O3/client -I$O3 ovpncli.i

echo CORE
$GPP_CMD \
    --sysroot=$NDK/platforms/android-9/arch-arm \
    -DAPP_EXPIRE_TIME=1346479200 \
    -O3 -fPIC \
    -Wall -Wno-sign-compare -Wno-unused-parameter \
    -fvisibility=hidden \
    -DUSE_OPENSSL \
    -D__GLIBC__ \
    -D_GLIBCXX_HAVE_FENV_H=1 \
    -DBOOST_NO_INTRINSIC_WCHAR_T \
    -I$O3/client \
    -I$O3 \
    -I$BOOST_DIR \
    -I$OPENSSL_DIR/include \
    -c $O3/client/ovpncli.cpp

echo WRAP
$GPP_CMD \
    --sysroot=$NDK/platforms/android-9/arch-arm \
    -Os -fPIC \
    -fno-strict-aliasing \
    -Wall \
    -fvisibility=hidden '-DSWIGEXPORT=__attribute__((visibility("default")))' \
    -D__GLIBC__ \
    -D_GLIBCXX_HAVE_FENV_H=1 \
    -I$O3/client \
    -I$O3 \
    -L$BOOST_DIR/stage/lib \
    -L$OPENSSL_DIR/lib \
    ovpncli_wrap.cxx \
    ovpncli.o \
    -o libovpncli.so \
    -shared -Wl,-soname,libovpncli.so \
    -lssl -lcrypto \
    -lboost_system -lboost_thread

echo STRIP
$STRIP_CMD libovpncli.so
mv SWIGTYPE_p_std__string.java ClientAPI_*.java libovpncli.so pt/
