#ifndef OPENVPN_GENCRYPTO_APPLECRYPTO_H
#define OPENVPN_GENCRYPTO_APPLECRYPTO_H

#if defined(__APPLE__) && !defined(USE_OPENSSL)
#define OPENVPN_APPLE_CRYPTO
#endif

#endif // OPENVPN_GENCRYPTO_APPLECRYPTO_H
