#ifndef OPENVPN_APPLECRYPTO_CRYPTO_EVPCOMMON_H
#define OPENVPN_APPLECRYPTO_CRYPTO_EVPCOMMON_H

namespace openvpn {

  struct ENGINE {};

} // namespace openvpn

#endif // OPENVPN_APPLECRYPTO_CRYPTO_EVPCOMMON_H
