#!/usr/bin/env bash
# sample usage: PSSL=1 MINI=1 ./build-mac-static
set -e
rm -f libovpncli.a ovpncli.o
ECHO=1 CO=1 build $OVPN3_DIR/client/ovpncli
ar crs libovpncli.a ovpncli.o
./make-dist dist-static-$PLATFORM libovpncli.a
if [ -d "$OPENSSL_DIR" ]; then
    cp $OPENSSL_DIR/lib/*.a dist-static-$PLATFORM/lib
fi
if [ -d "$POLARSSL_DIR" ]; then
    cp $POLARSSL_DIR/library/*.a dist-static-$PLATFORM/lib
fi
cp $BOOST_DIR/$BOOST_STAGE/*.a dist-static-$PLATFORM/lib
