#!/usr/bin/env bash

set -e
if [ -z "$O3" ]; then
    echo O3 var must point to ovpn3 tree
    exit 1
fi

rm -rf polarssl
mkdir polarssl

# for ios, build with minicrypto
for target in ios-dbg ios ; do
    echo '***************' TARGET $target
    VERBOSE=1 TARGET=$target USE_MINICRYPTO=1 MINICRYPTO_DIR=$(pwd)/minicrypto/minicrypto-$target $O3/polarssl/build-polarssl
    mv polarssl-$target polarssl

    [ "$IOS_DBG_ONLY" = "1" ] && exit
done

# all except ios device
for target in osx osx-dbg iossim iossim-dbg ; do
    echo '***************' TARGET $target
    VERBOSE=1 TARGET=$target $O3/polarssl/build-polarssl
    mv polarssl-$target polarssl/
done
