#!/usr/bin/env bash

set -e
[ "$DEP_DIR" ] && cd $DEP_DIR
if [ -z "$O3" ]; then
    echo O3 var must point to ovpn3 tree
    exit 1
fi
if [ -z "$DEP_DIR" ]; then
    echo DEP_DIR var must point to ovpn3 dependency tree
    exit 1
fi
cd $DEP_DIR

rm -rf minicrypto
mkdir minicrypto

for target in ios-dbg ios ; do
    echo '***************' TARGET $target
    TARGET=$target $O3/minicrypto/build-minicrypto
done
exit 0
