#!/usr/bin/env bash

set -e
if [ -z "$O3" ]; then
    echo O3 var must point to ovpn3 tree
    exit 1
fi

rm -rf lz4
mkdir lz4

if [ "$OSX_ONLY" != "1" ]; then
    for target in ios ios-dbg iossim iossim-dbg ; do
	echo '***************' TARGET $target
	TARGET=$target $O3/lz4/build-lz4
    done
fi

for target in osx osx-dbg ; do
    echo '***************' TARGET $target
    TARGET=$target $O3/lz4/build-lz4
done
