#!/usr/bin/env bash
set -e
export BOOST=boost_1_49_0
. $O3/vars-iossim
export PLATFORM_FLAGS_SIM="$PLATFORM_FLAGS"
. $O3/vars-ios
rm -rf $BOOST
if [ "$SRCDIR" ]; then
    cp -a "$SRCDIR" $BOOST
else
    tar xfj ~/Downloads/$BOOST.tar.bz2
fi
cd $BOOST
patch -p1 <$DL/asio-engine.patch
cat >>tools/build/v2/user-config.jam <<EOF
using clang : ios : clang++
            :
                <compileflags>"-Wno-unused-function $PLATFORM_FLAGS $OTHER_COMPILER_FLAGS"
            ;
using clang : iossim : clang++
            :
                <compileflags>"-Wno-unused-function $PLATFORM_FLAGS_SIM $OTHER_COMPILER_FLAGS"
            ;
using clang : osx : clang++
            :
                <compileflags>"-Wno-unused-function $OTHER_COMPILER_FLAGS"
            ;
EOF
./bootstrap.sh
for target in ios iossim osx ; do
    ./bjam -d2 toolset=clang-$target --stagedir=stage-$target --with-system --with-thread variant=release link=static threading=multi runtime-link=static
done
