#!/usr/bin/env bash
set -e
if [ -z "$O3" ]; then
    echo O3 var must point to ovpn3 tree
    exit 1
fi
cd ~/src/mac
rm -rf boost* lz4* lzo* minicrypto openssl* polarssl* snappy*
echo "******* BOOST"
$O3/scripts/mac/build-boost
echo "******* POLARSSL"
$O3/scripts/mac/build-polarssl
echo "******* SNAPPY"
$O3/scripts/mac/build-snappy
echo "******* LZ4"
$O3/scripts/mac/build-lz4
