#!/usr/bin/env bash

set -e
if [ -z "$O3" ]; then
    echo O3 var must point to ovpn3 tree
    exit 1
fi

mini=1
[ "$DISABLE_MINICRYPTO" = "1" ] && mini=0

rm -rf polarssl
mkdir polarssl

if [ "$OSX_ONLY" != "1" ]; then
    # for ios, build with minicrypto
    for target in ios-dbg ios ; do
	echo '***************' TARGET $target
	VERBOSE=1 TARGET=$target USE_MINICRYPTO=$mini MINICRYPTO_DIR=$(pwd)/minicrypto/minicrypto-$target $O3/polarssl/build-polarssl
	mv polarssl-$target polarssl
	[ "$IOS_DBG_ONLY" = "1" ] && exit
    done

    # ios simulators
    for target in iossim iossim-dbg ; do
	echo '***************' TARGET $target
	VERBOSE=1 TARGET=$target $O3/polarssl/build-polarssl
	mv polarssl-$target polarssl/
    done
fi

# osx
[ -z "$OSX_MINICRYPTO" ] && OSX_MINICRYPTO=0
for target in osx osx-dbg ; do
    echo '***************' TARGET $target
    VERBOSE=1 TARGET=$target USE_MINICRYPTO=$OSX_MINICRYPTO ENABLE_SERVER=1 $O3/polarssl/build-polarssl
    mv polarssl-$target polarssl/
done
