#!/usr/bin/env bash
set -e
if [ -z "$O3" ]; then
    echo O3 var must point to ovpn3 tree
    exit 1
fi
export DEP_DIR=${DEP_DIR:-$HOME/src/mac}
cd $DEP_DIR
rm -rf boost* lz4* lzo* minicrypto openssl* polarssl* snappy*
echo "******* BOOST"
$O3/scripts/mac/build-boost
echo "******* MINICRYPTO"
$O3/scripts/mac/build-minicrypto
echo "******* POLARSSL"
OSX_SERVER=0 $O3/scripts/mac/build-polarssl
echo "******* SNAPPY"
$O3/scripts/mac/build-snappy
echo "******* LZ4"
$O3/scripts/mac/build-lz4
exit 0
