#!/usr/bin/env bash

set -e
if [ -z "$O3" ]; then
    echo O3 var must point to ovpn3 tree
    exit 1
fi

rm -rf minicrypto
mkdir minicrypto

for target in ios-dbg ios ; do
    echo '***************' TARGET $target
    TARGET=$target $O3/minicrypto/build-minicrypto
done
