#!/usr/bin/env bash
set -e

SMOD=$O3/scripts/smod
rm -rf ~/Library/Developer/Xcode/DerivedData
rm -rf OpenVPN
cp -a ~/src/AppleVPNSample OpenVPN

cd OpenVPN
rm -rf $(find . -type d -name .svn)
rm -f $(find . | grep -E '\.(DS_Store)$')
rm -rf Build_VPN_App_and_Plugin.pdf Security SystemConfiguration

mv VPNSample.xcodeproj OpenVPN.xcodeproj
mv VPNPluginSample OpenVPNPlugin
mv VPNAppSample-EMBEDDED OpenVPNApp-EMBEDDED
mv VPNAppSample-MacOS OpenVPNApp-MacOS

rm -rf OpenVPN.xcodeproj/project.xcworkspace
rm -rf OpenVPN.xcodeproj/xcuserdata

$SMOD -f VPNSample -t OpenVPN replace
$SMOD -f VPNPluginSample -t OpenVPNPlugin replace
$SMOD -f VPNAppSample -t OpenVPNApp replace

$SMOD -f VPNSample -t OpenVPN replace-path
$SMOD -f VPNPluginSample -t OpenVPNPlugin replace-path
$SMOD -f VPNAppSample -t OpenVPNApp replace-path
