#!/usr/bin/env bash
if [ -z "$1" ]; then
    echo "usage: ./build target"
    echo "options:"
    echo " CLANG=1 -- use clang instead of gcc"
    echo " DEBUG=1 -- enable debug"
    echo ' ECHO=1 -- show commands'
    echo " STRIP=1 -- strip binary"
    echo " STRICT=1 -- more warnings"
    echo " LTO=1 -- build with LTO"
    echo " GPROF=1 -- build for gprof profiling"
    echo " PGEN=1 -- generate data for profile-guided optimization"
    echo " PUSE=1 -- use data from previous run of PGEN=1 build"
    echo " PSSL=1 -- include PolarSSL"
    echo " NOSSL=1 -- don't include OpenSSL (non-mac)"
    echo " MINI=1 -- link with OpenSSL mini crypto lib"
    echo " OSSL=1 -- include OpenSSL on Mac"
    echo " SSL_BOTH=1 -- include OpenSSL and Apple SSL on Mac"
    echo " NOTHREADS=1 -- disable threads"
    echo ' GCC_EXTRA="-DITER=5" -- add build flags'
    echo " LZO=1 -- build with LZO compression library"
    echo " LZ4=1 -- build with LZ4 compression library"
    echo " SNAP=1 -- build with Snappy compression library"
    exit 1
fi

# remove previous build
rm -f $1

# build options
CPPFLAGS=""
LIBS=""
LIBDIRS=""
EXTRA_SRC_OBJ=""

# clang support
if [ "$CLANG" = "1" ]; then
    [ -z "$GPP_CMD" ] && GPP_CMD=clang++
fi

# default commands
[ -z "$STRIP_CMD" ] && STRIP_CMD=strip
[ -z "$GPP_CMD" ] && GPP_CMD=g++

# build flags
FLAGS="-Wall"
[ "$STRICT" = "1" ] && FLAGS="$FLAGS -Wextra"
[ "$CLANG" = "1" ] && FLAGS="$FLAGS -Wno-tautological-compare -Wno-deprecated-declarations"
FLAGS="$FLAGS -Wno-sign-compare -Wno-unused-parameter"

# PolarSSL
if [ "$PSSL" = "1" ]; then
    LIBS="$LIBS -lpolarssl"
    CPPFLAGS="$CPPFLAGS -DUSE_POLARSSL -I$POLARSSL_DIR/include"
    LIBDIRS="$LIBDIRS -L$POLARSSL_DIR/library"
    if [ "$MINI" = "1" ]; then
	LIBS="$LIBS -lminicrypto"
	LIBDIRS="$LIBDIRS -L$OPENSSL_DIR/lib"
	NOSSL=1
    fi
fi

# OpenSSL
if [ "$PLATFORM" = "mac" ] || [ "$PLATFORM" = "ios" ]; then
    # On Mac, only link with OpenSSL if OSSL is defined.
    # On other platforms, always link with OpenSSL.
    if [ "$SSL_BOTH" = "1" ]; then
	CPPFLAGS="$CPPFLAGS -DUSE_APPLE_SSL -DUSE_OPENSSL"
	LIBS="$LIBS -lcrypto -lssl -framework Security"
    else
	if [ "$OSSL" = "1" ]; then
	    CPPFLAGS="$CPPFLAGS -DUSE_OPENSSL"
	    LIBS="$LIBS -lcrypto -lssl"
	else
	    CPPFLAGS="$CPPFLAGS -DUSE_APPLE_SSL"
	    LIBS="$LIBS -framework Security"
	fi
    fi

    # Include other Mac frameworks
    # -framework CoreServices
    LIBS="$LIBS -framework CoreFoundation"
else
    if [ "$NOSSL" != "1" ]; then
	CPPFLAGS="$CPPFLAGS -DUSE_OPENSSL"
	LIBS="$LIBS -lssl -lcrypto -ldl"
    fi
fi
if [ "$OPENSSL_DIR" ] && [ "$NOSSL" != "1" ]; then
    CPPFLAGS="$CPPFLAGS -I$OPENSSL_DIR/include"
    LIBDIRS="$LIBDIRS -L$OPENSSL_DIR/lib"
fi

# boost
CPPFLAGS="$CPPFLAGS -I$BOOST_DIR"
LIBS="$LIBS -lboost_system"
LIBDIRS="$LIBDIRS -L$BOOST_DIR/stage/lib"
if [ "$NOTHREADS" = "1" ]; then
    CPPFLAGS="$CPPFLAGS -DBOOST_DISABLE_THREADS"
else
    LIBS="$LIBS -lboost_thread"
    [ "$PLATFORM" != "android" ] && FLAGS="$FLAGS -pthread"
fi

# LZO compression
if [ "$LZO" = "1" ]; then
    LIBS="$LIBS -llzo2"
    CPPFLAGS="$CPPFLAGS -DHAVE_LZO"
fi

# LZ4 compression
if [ "$LZ4" = "1" ]; then
    EXTRA_SRC_OBJ="$EXTRA_SRC_OBJ $LZ4_DIR/lz4.o"
    CPPFLAGS="$CPPFLAGS -I$LZ4_DIR -DHAVE_LZ4"
fi

# Snappy compression
if [ "$SNAP" = "1" ]; then
    if [ "$SNAPPY_DIR" ]; then
	LIBDIRS="$LIBDIRS -L$SNAPPY_DIR/lib"
	CPPFLAGS="$CPPFLAGS -I$SNAPPY_DIR/include"
    fi
    LIBS="$LIBS -lsnappy"
    CPPFLAGS="$CPPFLAGS -DHAVE_SNAPPY"
fi

# Android NDK
if [ "$PLATFORM" = "android" ]; then
    FLAGS="$FLAGS --sysroot=$NDK/platforms/android-9/arch-arm"
    CPPFLAGS="$CPPFLAGS -D__GLIBC__"
    CPPFLAGS="$CPPFLAGS -D_GLIBCXX_HAVE_FENV_H=1"
    CPPFLAGS="$CPPFLAGS -DBOOST_NO_INTRINSIC_WCHAR_T"
fi

# iOS
if [ "$PLATFORM" = "ios" ]; then
    FLAGS="$FLAGS -arch armv7 -miphoneos-version-min=5.0 -isysroot /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS5.0.sdk"
fi

# ovpn3
CPPFLAGS="$CPPFLAGS -I$OVPN3_DIR"

# profile-guided optimization
if [ "$PGEN" = "1" ]; then
    FLAGS="$FLAGS -fprofile-generate"
elif [ "$PUSE" = "1" ]; then
    FLAGS="$FLAGS -fprofile-use"
fi

# optimization level
if [ "$LTO" = "1" ] && [ "$CLANG" == "1" ]; then
    FLAGS="-O4 $FLAGS"
else
    FLAGS="-O3 $FLAGS"
fi

# whole-program
FLAGS="-fwhole-program $FLAGS"

# release/debug builds
if [ "$DEBUG" = "1" ]; then
    # debug build
    CMD="$GPP_CMD -g $FLAGS $GCC_EXTRA $CPPFLAGS $LIBDIRS $1.cpp $EXTRA_SRC_OBJ -o $1 $LIBS"
else
    # release build
    [ "$LTO" = "1" ] && [ "$CLANG" != "1" ] && FLAGS="$FLAGS -flto=4 -Wl,--no-as-needed"
    [ "$GPROF" = "1" ] && FLAGS="$FLAGS -pg"
    CMD="$GPP_CMD $FLAGS $GCC_EXTRA $CPPFLAGS $LIBDIRS $1.cpp $EXTRA_SRC_OBJ -o $1 $LIBS"
fi

# execute CMD
[ "$ECHO" = "1" ] && echo $CMD
$CMD

# maybe strip
[ "$STRIP" = "1" ] && $STRIP_CMD $1
exit 0
